version: '2'
services:
  db:
    image: mysql:8
    ports:
    - "3306:3306"
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=mf
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    volumes:
    - $PWD/db/initdb.d:/docker-entrypoint-initdb.d

  exporter:
    depends_on:
    - db
    environment:
    # port here should be the same as below
    - DBDIFF_GRAPI_HOST=http://localhost:8082

  grapi:
    ports:
      # using 8082 because the 8081 port on my dev server is already taken
      - "8082:8081"
