version: '2'
services:
  grapi:
    build:
      context: grapi
      dockerfile: Dockerfile
    environment:
    - LOGLEVEL=info
    volumes:
    - /data/docker-db-diff/grapi/:/tmp/git/1161017-23323-pfc5zt/

  exporter:
    build:
      context: exporter
      dockerfile: Dockerfile
    depends_on:
    - grapi
    environment:
    - DBDIFF_GRAPI_HOST=http://grapi:8081
    volumes:
    - ./exporter/etc/odbc/:/code/exporter/etc/odbc/:ro
    - ./exporter/etc/cron.d/:/code/exporter/etc/cron.d/:ro
    - ./exporter/etc/swiftmailer/:/code/exporter/etc/swiftmailer/:ro
